config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :sharks, only: [:index, :show]
  resources :bookings, only: [:create]
  namespace :owner do
    resource :dashboards, only: [:show]
    resources :sharks, only: [:new, :create]
    resources :bookings, only: [] do
      member do
        patch :accept
        patch :decline
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :shark
  belongs_to :renter, class_name: :User, foreign_key: :renter_id
end

app/models/shark.rb
class Shark < ApplicationRecord
  belongs_to :owner, class_name: :User, foreign_key: :owner_id
  has_many :bookings, dependent: :destroy
  has_many_attached :photos

  validates :name, presence: true
  validates :description, presence: true
  validates :price_per_day, presence: true
  validates :address, presence: true
  validates :weight, presence: true
  validates :photos, presence: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :sharks, foreign_key: :owner_id
  has_many :bookings, foreign_key: :renter_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def create
    @shark = Shark.find(params[:booking][:shark_id])
    @booking = Booking.new(booking_params)
    @booking.shark = @shark
    @booking.renter = current_user
    if @booking.save
      redirect_to owner_dashboards_path
    else
      render "sharks/show", status: :unprocessable_entity
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :ending_date, :shark_id)
  end
end

app/controllers/owner/bookings_controller.rb
class Owner::BookingsController < ApplicationController
  def accept
    @booking = Booking.find(params[:id])
    @booking.status = 'accepted'
    @booking.save
    redirect_to owner_dashboards_path, notice: 'Réservation acceptée avec succès.'
  end

  def decline
    @booking = Booking.find(params[:id])
    @booking.status = 'declined'
    @booking.save
    redirect_to owner_dashboards_path, notice: 'Réservation déclinée avec succès.'
  end
end

app/controllers/owner/dashboards_controller.rb
class Owner::DashboardsController < ApplicationController
  def show
    @user_bookings = current_user.bookings.where(status: 'pending')
    @validate_bookings = current_user.bookings.where(status: 'accepted')
    @incoming_bookings = Booking.includes(:shark).where(shark: { owner: current_user }).where(status: 'pending')
    @sharks = current_user.sharks
  end
end

app/controllers/owner/sharks_controller.rb
class Owner::SharksController < ApplicationController
  def new
    @shark = Shark.new
  end

  def create
    @shark = Shark.new(shark_params)
    @shark.owner = current_user

    if @shark.save
      redirect_to owner_dashboards_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def shark_params
    params.require(:shark).permit(:name, :description, :price_per_day, :address, :weight, :skills, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/sharks_controller.rb
class SharksController < ApplicationController
  def index
    @sharks = Shark.all
    @markers = @sharks.geocoded.map do |shark|
      {
        lat: shark.latitude,
        lng: shark.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {shark: shark})
      }
    end
  end

  def show
    @shark = Shark.find(params[:id])
    @booking = Booking.new
    @marker = [{
      lat: @shark.latitude,
      lng: @shark.longitude,
      info_window_html: render_to_string(partial: "info_window", locals: {shark: @shark})
    }]

  end

  private

  def shark_params
    params.require(:shark).permit(:name, :description, :price_per_day, :photos[])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This website is made with <i class="fas fa-heart"></i> by Jade, Frédérique, Qian & Clothilde, at Le Wagon
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid ">
    <%= link_to "/", class: "navbar-brand" do %>
      <i class="fa-solid fa-fish-fins"></i>
    <% end %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
              <div class="row justify-content-left">
                  <div class="col-sm-8 my-3">
                    <%= form_with url: sharks_path, method: :get, class: "d-flex" do %>
                      <%= text_field_tag :query,
                            params[:query],
                            class: "form-control searchbar",
                            placeholder: "Chercher un poisson"%>
                      <%= submit_tag "Search", name: "", class: "btn btn-primary" %>
                    <% end %>
                  </div>
                </div>
          </li>
          <li class="nav-item active">
            <%= link_to "Home", "/", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Fishes", sharks_path, class: "nav-link" %>
          </li>
          <div class="btn-nav">
            <li class="nav-item dropdown">
              <i class="fa-solid fa-bars" style="color: #6b6b6b;"></i>
              <%= image_tag "https://static.vecteezy.com/system/resources/previews/018/765/757/original/user-profile-icon-in-flat-style-member-avatar-illustration-on-isolated-background-human-permission-sign-business-concept-vector.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Gérer mes réservations", owner_dashboards_path, class: "dropdown-item" %>
                <%= link_to "Gérer mes poissons", owner_dashboards_path, class: "dropdown-item" %>
                <%= link_to "Déconnexion", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
              </div>
            </li>
          </div>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoldfishesApp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <script src="https://kit.fontawesome.com/9b8a7e18a0.js"></script>

    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div class="white">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <%= render "layouts/navbar" %>

    <%= yield %>
    
  </div>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/owner/dashboards/show.html.erb
<div class="container">
  <h1 class="mt-3">Mon profil</h1>
  <div class="row">
    <div class="col-md-4">
      <ul class="list-group">
        <div class="row">
          <div class="col-md-8">
            <h5>Mes poissons</h5>
          </div>
          <div class="col-md-4 text-end">
            <%= link_to new_owner_shark_path, class: "blue" do %>
              <i class="fa-solid fa-plus fa-lg" style="color: #00a6cf;"></i>
            <% end %>
          </div>
        </div>
        <div class="border-top"></div>
        <% @sharks.where(owner: current_user).each do |shark| %>
          <li class="list-group-item">
            <div style="display: flex; align-items: center;">
            <%= cl_image_tag shark.photos.first.key, style: "width: 30px; height: 30px; margin-right: 10px; border-radius: 50%" %>
            <%= link_to shark.name, shark_path(shark) %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>

    <div class="col-md-8">
      <h3>En cours de validation</h3>
        <% if @user_bookings.present?%>
        <p> Le propriétaire validera bientôt votre réservation</p>
          <div class="cards">
            <% @user_bookings.each do |booking| %>
              <%= link_to shark_path(booking.shark), class: "text-decoration-none", style: "color: inherit" do %>
                <div class="card-product">
                    <%= cl_image_tag booking.shark.photos.first.key %>
                  <div class="card-product-infos">
                    <h4><%= booking.shark.name %></h4>
                    <p><%= truncate(booking.shark.description, length:50) %></p>
                    <%= booking.start_date.strftime("%d %B") %> - <%= booking.ending_date.strftime("%d %B") %>
                    <% number_of_days = booking.ending_date - booking.start_date %>
                    <% total_price = booking.shark.price_per_day * number_of_days %>
                    <p><%= total_price %> €</p>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
        <% else %>
          <p>Oups! Aucune réservation trouvée.</p>
        <% end %>

      <h3>Validés</h3>

      <div class="cards">
        <% if @validate_bookings.present?%>
          <% @validate_bookings.each do |booking| %>
            <%= link_to shark_path(booking.shark), class: "text-decoration-none", style: "color: inherit" do %>
              <div class="card-product">
                <%= cl_image_tag booking.shark.photos.first.key %>
                <div class="card-product-infos">
                  <h4><%= booking.shark.name %></h4>
                  <p><%= booking.shark.description %></p>
                  <%= booking.start_date.strftime("%d %B") %> - <%= booking.ending_date.strftime("%d %B") %>
                  <% number_of_days = booking.ending_date - booking.start_date %>
                  <% total_price = booking.shark.price_per_day * number_of_days %>
                  <p><%= total_price %> €</p>
                </div>
              </div>
            <% end %>
          <% end %>
        <% else %>
          <p>Oups! Aucune réservation trouvée.</p>
        <% end %>
      </div>

      <div class="border-top"></div>

        <h3>En attente de validation</h3>
          <p>Ces poissons demandent à être loués, veuillez accepter ou refuser la location.</p>
        <div class="cards">
        <% @incoming_bookings.each do |booking| %>
          <div class="card-product">
            <%= cl_image_tag booking.shark.photos.first.key %>
              <div class="card-product-infos">
                <h4><%= booking.shark.name %></h4>
                <p><%= booking.start_date.strftime("%d %B") %> - <%= booking.ending_date.strftime("%d %B") %></p>
                <% number_of_days = booking.ending_date - booking.start_date %>
                <% total_price = booking.shark.price_per_day * number_of_days %>
                <p><%= total_price %> €</p>
                <div style="position:relative;left:200px">
                  <%= link_to "Accepter", accept_owner_booking_path(booking), data: {turbo_method: :patch}, class: "btn btn-light"%>
                  <%= link_to "Décliner", decline_owner_booking_path(booking), data: {turbo_method: :patch}, class: "btn btn-light"%>
                </div>
              </div>
            </div>
          <% end %>
        </div>
    </div>
  </div>
</div>

app/views/owner/sharks/new.html.erb
<div class="container mt-3 d-flex">
  <div class="p-2 w-100">
    <h1>Ajouter un poisson</h1>
    <p>Renseignez les informations suivantes :</p>
      <%= simple_form_for([:owner,@shark]) do |f| %>
      <%= f.input :name, :label => 'Nom du poisson' %>
      <%= f.input :description, :as => :string, :label => 'Bio' %>
      <%= f.input :price_per_day, :label => 'Prix par jour' %>
      <%= f.input :address,:label => 'Adresse' %>
      <%= f.input :weight, :label => 'Poids' %>
      <%= f.input :skills, :label => 'Technique spéciale' %>
      <%= f.input :photos, as: :file, input_html: { multiple: true } %>
      <%= f.submit 'Ajouter mon poisson', class:"button-frozen" %>
    <% end %>
  </div>
  <div class="p-2 flex-shrink-1">
    <%= link_to 'Retour', owner_dashboards_path, class: "button-frozen"%>
  </div>

</div>

app/views/pages/home.html.erb
<div class="center m-4">
<h1 class="center mt-3">Ici retrouvez tous les meilleurs poissons du Monde !</h1>

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.5)), url(https://images.unsplash.com/photo-1578507065211-1c4e99a5fd24?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D);">
  <div class="container">
    <h1>Goldfish app vous propose <strong>des poissons</strong> pour <strong>tous les types de films</strong>!</h1>

    <p>Faites un carton au box-office avec nos poissons célèbres.</p>
    <p>Découvrez des poissons inconnus du grand public pour vos films d'auteur.
    Connus ou non, nos poissons sont des professionnels.</p>
  <% if user_signed_in? %>
  <div class="mt-5">
    <%= link_to "Voir les poissons", sharks_path, class: "button-frozen mt-5", id:"btn-top"  %>
  </div>
    <% else %>
    <%= link_to "S'inscrire", new_user_session_path, class: "button-frozen", id:"btn-top"  %>
    <%= link_to "Se connecter", user_session_path, class: "button-contour" %>
    <% end %>
    </div>
</div>

</div>

app/views/sharks/_info_window.html.erb
<h2><%= shark.name %></h2>
<p><%= shark.address %></p>

app/views/sharks/index.html.erb
<div class="container mt-3">
<h1>Nos poissons à louer</h1>
<p>Faites votre choix parmi les propositions ci-dessous:</p>
<div class="card-wrap cards">

  <% @sharks.each do | shark | %>
    <%= link_to shark_path(shark), class:"text-decoration-none", style:"color: inherit" do %>
      <div class="card-product">
        <%= cl_image_tag shark.photos.first.key %>
        <div class="card-product-infos">
          <h2><%= shark.name %></h2>
          <p>Bio: <%= truncate(shark.description, length:50) %></p>
          <p id="price-per-day" style="position:relative;left:330px;"> € <%= shark.price_per_day %>/jour <p>
          </div>
      </div>
      <% end %>
    <% end %>
</div>

<div style="width: 100%; height: 400px; p-20" class="photo"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
  </div>

app/views/sharks/show.html.erb
<div class="container mt-3">
  <h2><%= @shark.name %> <i class="fa-solid fa-fish-fins" style="color: #ffc000;"></i><i class="fa-solid fa-fish-fins" style="color: #ffc000;"></i><i class="fa-solid fa-fish-fins" style="color: #ffc000;"></i><i class="fa-solid fa-fish-fins" style="color: #ffc000;"></i><i class="fa-solid fa-fish-fins" style="color: #ffc000;"></i></h2>
  <br>
    <div class="container mt-3 d-flex justify-content-center">
      <% if @shark.photos.attached? %>
        <% @shark.photos.each do |photo| %>
        <%= cl_image_tag photo.key, class: "photo-30" %>
        <% end %>
      <% else %>
      <% end %>
    </div>
<br>
<br>
  <div class="d-flex justify-content-center">

    <div class="card-info-show">
      <p><i class="fa-regular fa-address-card" style="color: #7fc8f8;" alt="Bio"></i> <%= @shark.description %></p>
      <p><i class="fa-solid fa-wand-magic-sparkles" style="color: #7fc8f8;"></i> <%= @shark.skills %></p>
      <p><i class="fa-solid fa-weight-hanging" style="color: #7fc8f8;"></i> <%= @shark.weight %></p>
      <p><i class="fa-solid fa-location-dot" style="color: #7fc8f8;"></i> <%= @shark.address %></p>
      <div class="border-top"></div>
      <div style="display: flex; align-items: center;">
        <%= image_tag "https://static.vecteezy.com/system/resources/previews/018/765/757/original/user-profile-icon-in-flat-style-member-avatar-illustration-on-isolated-background-human-permission-sign-business-concept-vector.jpg", style: "width: 60px; height: 60px; margin-right: 10px; border-radius: 50%; margin-bottom:50px" %>
        <div>
          <p><strong>Propriétaire : <%= @shark.owner.first_name %></strong></p>
          <p style="color: #717171;">Super pêcheur depuis 12 ans</p>
        </div>
      </div>

    </div>

    <div class="map-show"
      data-controller="map"
      data-map-markers-value="<%= @marker.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>

      <div class="form-container">
        <div class="large">
          <div class = "card-simple-form" >
            <p><strong><%= @shark.price_per_day %></strong>€ par jour </p>
            <%= simple_form_for(@booking) do |f| %>
              <%= f.error_notification %>
              <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
                <div class="form-inputs">
                  <%= f.input :start_date,
                              as: :string,
                              input_html: { data: { controller: "datepicker" } }%>
                  <%= f.input :ending_date,
                              as: :string,
                              input_html: { data: { controller: "datepicker" } }%>
                  <%= f.input :shark_id, input_html: {value: params[:id]}, as: :hidden %>
                </div>

              <div class="form-actions">
                <%= f.button :submit, class: "button-frozen"%>
              </div>
            <% end %>
          </div>
        </div>
    </div>
  </div>
</div>